apiVersion: v1
kind: Service
metadata:
  name: hello-docker
spec:
  type: LoadBalancer
  selector:
    app: hello-docker
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-docker-deploy
spec:
  selector:
    matchLabels:
      app: hello-docker
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-docker
    spec:
      containers:
      - name: hello-docker-pod
        image: mohebbadawy/hello-docker:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 10